module.exports = (req, res, next) => {
  const ua = req.get("User-Agent");
  const isBlackList = blackList.some((string) =>
    ua.toLocaleLowerCase().includes(string.toLocaleLowerCase())
  );

  if (isBlackList || process.env.STOP_SITE == "true")
    return res.status(500).send();
  next();
};

const blackList = [
  "almaden",
  "Anarchie",
  "ASPSeek",
  "attach",
  "autoemailspider",
  "BackWeb",
  "Bandit",
  "BatchFTP",
  "BlackWidow",
  "Bot mailto:",
  "Buddy",
  "bumblebee",
  "CherryPicker",
  "ChinaClaw",
  "CICC",
  "Collector",
  "Copier",
  "Crescent",
  "Custo",
  "DA",
  "DIIbot",
  "DISCo",
  "DISCo Pump",
  "Download Demon",
  "Download Wonder",
  "Downloader",
  "Drip",
  "DSurf15a",
  "eCatch",
  "EasyDL/2.99",
  "EirGrabber",
  "EmailCollector",
  "EmailSiphon",
  "EmailWolf",
  "Express WebPictures",
  "ExtractorPro",
  "EyeNetIE",
  "FileHound",
  "FlashGet",
  "FrontPage",
  "GetRight",
  "GetSmart",
  "GetWeb!",
  "gigabaz",
  "GoZilla",
  "Go!Zilla",
  "Go-Ahead-Got-It",
  "gotit",
  "Grabber",
  "GrabNet",
  "Grafula",
  "grub-client",
  "HMView",
  "HTTrack",
  "httpdown",
  "httrack",
  "ia_archiver",
  "Image Stripper",
  "Image Sucker",
  "IndyLibrary",
  "Indy Library",
  "InterGET",
  "InternetLinkagent",
  "Internet Ninja",
  "InternetSeer.com",
  "Iria",
  "JBHagent",
  "JBH agent",
  "JetCar",
  "JOC Web Spider",
  "JustView",
  "larbin",
  "LeechFTP",
  "LexiBot",
  "lftp",
  "LinkSleuth",
  "Link Sleuth",
  "likse",
  "Link",
  "LinkWalker",
  "Mag-Net",
  "Magnet",
  "Mass Downloader",
  "Memo",
  "Microsoft.URL",
  "MIDown tool",
  "Mirror",
  "Mister PiX",
  "Mozilla.Indy",
  "Mozilla. Indy",
  "Mozilla Indy",
  "MozillaIndy",
  "Mozilla.NEWT",
  "Mozilla. NEWT",
  "MozillaNEWT",
  "Mozilla NEWT",
  "MozillaMSIECrawler",
  "Mozilla MSIECrawler",
  "MS FrontPage",
  "MSFrontPage",
  "MSIECrawler",
  "MSProxy",
  "Navroad",
  "NearSite",
  "NetAnts",
  "NetMechanic",
  "NetSpider",
  "Net Vampire",
  "NetZIP",
  "NICErsPRO",
  "Ninja",
  "Octopus",
  "Offline Explorer",
  "Offline Navigator",
  "Openfind",
  "PageGrabber",
  "Papa Foto",
  "pavuk",
  "pcBrowser",
  "Ping",
  "PingALink",
  "Pockey",
  "psbot",
  "Pump",
  "QRVA",
  "RealDownload",
  "Reaper",
  "Recorder",
  "ReGet",
  "Scooter",
  "Seeker",
  "Siphon",
  "SiteSnagger",
  "SlySearch",
  "SmartDownload",
  "Snake",
  "SpaceBison",
  "sproose",
  "Stripper",
  "Sucker",
  "SuperBot",
  "SuperHTTP",
  "Surfbot",
  "Szukacz",
  "tAkeOut",
  "Teleport Pro",
  "URLSpiderPro",
  "Vacuum",
  "VoidEYE",
  "Web Image Collector",
  "Web Sucker",
  "WebAuto",
  "Webbandit",
  "webcollage",
  "WebCopier",
  "Web Downloader",
  "WebEMailExtrac",
  "WebFetch",
  "WebGo IS",
  "WebHook",
  "WebLeacher",
  "WebMiner",
  "WebMirror",
  "WebReaper",
  "WebSauger",
  "Website",
  "Website eXtractor",
  "Website Quester",
  "Webster",
  "WebStripper",
  "WebSpider",
  "WebWhacker",
  "WebZIP",
  "Wget",
  "Whacker",
  "Widow",
  "WWWOFFLE",
  "x-Tractor",
  "Xaldon WebSpider",
  "Xaldon",
  "Xenu",
  "Zeus.Webster",
  "Zeus",
];
